[package]

name = "in_list_filter"
version = "0.0.1"
authors = ["Tibor Benke <ihrwein@gmail.com>"]

[lib]

name = "in_list_filter"
crate-type = ["dylib"]

[dependencies.syslog_ng_rust]
path = "../syslog_ng_rust/"
